# Python for Data Science Tutorial

We will be working with **large dataset**, the **World Development Indicators (WDI)** from the **World Bank**.<br/>

Alternatively you can download this dataset (`'WDI_csv.zip'`) from [here](https://datacatalog.worldbank.org/dataset/world-development-indicators)  

By the end of this tutorial you will learn to:

* Extract data from a `CSV file` and convert it to a `Pandas DataFrame`
* Create your own function using `zip()` to combine`lists` into a `Dictionary`

## 1) Extracting Data from Twitter CSV using Pandas

Using Pandas we will create a DataFrame of the WDI data `(world_ind_pop_data.csv)`

### * Importing Data

In [25]:
# Importing dependencies

import pandas as pd

In [26]:
# # Import World Development Indicators (WDI) data as DataFrame: df
wdi_df = pd.read_csv('world_ind_pop_data.csv')

### * Visualize Data

* Using the `.head()` method to view a quick summary of our data
* Using the `.info()` method to verify the type of data, number of rows and more

In [27]:
wdi_df.head()

,CountryName,CountryCode,Year,Total Population,Urban population (% of total)
0,Arab World,ARB,1960,9.249590e+07,31.285384
1,Caribbean small states,CSS,1960,4.190810e+06,31.597490
2,Central Europe and the Baltics,CEB,1960,9.140158e+07,44.507921
3,East Asia & Pacific (all income levels),EAS,1960,1.042475e+09,22.471132
4,East Asia & Pacific (developing only),EAP,1960,8.964930e+08,16.917679

In [28]:
wdi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13374 entries, 0 to 13373
Data columns (total 5 columns):
CountryName                      13374 non-null object
CountryCode                      13374 non-null object
Year                             13374 non-null int64
Total Population                 13374 non-null float64
Urban population (% of total)    13374 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 522.5+ KB

## 2) Dictionaries for Data Science

### * Using Zip function to create Dictionaries

* We will extract **two lists** from the DataFrame to practice
* We will use the `zip()` and `dict()` functions to combine the two lists into a dictionary

In [34]:
# List containing header names of the dataset
feature_names = list(wdi_df)
# List containing actual values of the first row
row_vals = list(wdi_df.iloc[0])

In [35]:
feature_names

['CountryName',
 'CountryCode',
 'Year',
 'Total Population',
 'Urban population (% of total)']

In [36]:
row_vals

['Arab World', 'ARB', 1960, 92495902.0, 31.285384211605397]

In [37]:
# Zip lists: zipped_lists
zipped_lists = zip(feature_names, row_vals)

# Create a dictionary: rs_dict
rs_dict = dict(zipped_lists)

rs_dict

{'CountryName': 'Arab World',
 'CountryCode': 'ARB',
 'Year': 1960,
 'Total Population': 92495902.0,
 'Urban population (% of total)': 31.285384211605397}

### * Writing a function to help you

In [39]:
def lists2dict(list1, list2):
    return dict(zip(list1, list2))

In [41]:
rs_fxn = lists2dict(feature_names, row_vals)
rs_fxn

{'CountryName': 'Arab World',
 'CountryCode': 'ARB',
 'Year': 1960,
 'Total Population': 92495902.0,
 'Urban population (% of total)': 31.285384211605397}

## 3) Creating 'world_dev_ind.csv' from 'WDIData.csv'

In [115]:
df = pd.read_csv('WDIData.csv')

In [116]:
print(df.columns)

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', 'Unnamed: 62'],
      dtype='object')

In [117]:
df1=df.iloc[:,:5].dropna()

In [118]:
df1.shape

(38447, 5)

In [119]:
print(df1.columns)

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960'],
      dtype='object')

In [147]:
# Appending a column 'Year' with the value '1960'
df1['Year'] ='1960'
print(df1.columns)

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', 'Year'],
      dtype='object')

In [121]:
df1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,Year
50,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1.342236e+02,1960
56,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,8.820581e+01,1960
57,Arab World,ARB,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,6.602746e+00,1960
58,Arab World,ARB,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,8.146539e+01,1960
94,Arab World,ARB,Aquaculture production (metric tons),ER.FSH.AQUA.MT,4.600000e+03,1960
101,Arab World,ARB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,3.000000e+06,1960
102,Arab World,ARB,Arms imports (SIPRI trend indicator values),MS.MIL.MPRT.KD,5.390000e+08,1960
138,Arab World,ARB,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,4.768996e+01,1960
145,Arab World,ARB,Broad money (% of GDP),FM.LBL.BMNY.GD.ZS,2.249595e+01,1960
151,Arab World,ARB,Capture fisheries production (metric tons),ER.FSH.CAPT.MT,4.748800e+05,1960
202,Arab World,ARB,"Claims on central government, etc. (% GDP)",FS.AST.CGOV.GD.ZS,4.083131e-01,1960
209,Arab World,ARB,CO2 emissions (kt),EN.ATM.CO2E.KT,5.953540e+04,1960
210,Arab World,ARB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,6.436890e-01,1960
212,Arab World,ARB,CO2 emissions from gaseous fuel consumption (%...,EN.ATM.CO2E.GF.ZS,5.041292e+00,1960
214,Arab World,ARB,CO2 emissions from liquid fuel consumption (% ...,EN.ATM.CO2E.LF.ZS,8.485147e+01,1960
215,Arab World,ARB,CO2 emissions from liquid fuel consumption (kt),EN.ATM.CO2E.LF.KT,5.053980e+04,1960
219,Arab World,ARB,CO2 emissions from solid fuel consumption (% o...,EN.ATM.CO2E.SF.ZS,4.726981e+00,1960
331,Arab World,ARB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,1.985420e+01,1960
362,Arab World,ARB,Domestic credit provided by financial sector (...,FS.AST.DOMS.GD.ZS,1.303565e+01,1960
363,Arab World,ARB,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1.224533e+01,1960
364,Arab World,ARB,Domestic credit to private sector by banks (% ...,FD.AST.PRVT.GD.ZS,1.167700e+01,1960
478,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.948747e+00,1960
615,Arab World,ARB,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,1.931232e+00,1960
712,Arab World,ARB,"International migrant stock, total",SM.POP.TOTL,3.324685e+06,1960
766,Arab World,ARB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,4.790606e+01,1960
767,Arab World,ARB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,4.577688e+01,1960
768,Arab World,ARB,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,4.682506e+01,1960
811,Arab World,ARB,Merchandise exports (current US$),TX.VAL.MRCH.CD.WT,4.644054e+09,1960
812,Arab World,ARB,Merchandise exports by the reporting economy (...,TX.VAL.MRCH.WL.CD,2.467200e+09,1960
813,Arab World,ARB,"Merchandise exports by the reporting economy, ...",TX.VAL.MRCH.RS.ZS,1.539397e+01,1960
...,...,...,...,...,...,...
419553,Zimbabwe,ZWE,"Population ages 70-74, female (% of female pop...",SP.POP.7074.FE.5Y,1.107699e+00,1960
419554,Zimbabwe,ZWE,"Population ages 70-74, male (% of male populat...",SP.POP.7074.MA.5Y,8.751079e-01,1960
419555,Zimbabwe,ZWE,"Population ages 75-79, female (% of female pop...",SP.POP.7579.FE.5Y,6.328797e-01,1960
419556,Zimbabwe,ZWE,"Population ages 75-79, male (% of male populat...",SP.POP.7579.MA.5Y,4.851363e-01,1960
419557,Zimbabwe,ZWE,"Population ages 80 and above, female (% of fem...",SP.POP.80UP.FE.5Y,4.106906e-01,1960
419558,Zimbabwe,ZWE,"Population ages 80 and above, male (% of male ...",SP.POP.80UP.MA.5Y,2.631747e-01,1960
419560,Zimbabwe,ZWE,Population growth (annual %),SP.POP.GROW,3.199877e+00,1960
419561,Zimbabwe,ZWE,Population in largest city,EN.URB.LCTY,2.479780e+05,1960
419562,Zimbabwe,ZWE,Population in the largest city (% of urban pop...,EN.URB.LCTY.UR.ZS,5.248567e+01,1960
419563,Zimbabwe,ZWE,Population in urban agglomerations of more tha...,EN.URB.MCTY,2.479780e+05,1960
419564,Zimbabwe,ZWE,Population in urban agglomerations of more tha...,EN.URB.MCTY.TL.ZS,6.617389e+00,1960
419567,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,1.879029e+06,1960
419568,Zimbabwe,ZWE,"Population, female (% of total)",SP.POP.TOTL.FE.ZS,5.014262e+01,1960
419569,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,1.868340e+06,1960
419570,Zimbabwe,ZWE,"Population, male (% of total)",SP.POP.TOTL.MA.ZS,4.985738e+01,1960
419571,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.747369e+06,1960
419771,Zimbabwe,ZWE,Rural population,SP.RUR.TOTL,3.274901e+06,1960
419772,Zimbabwe,ZWE,Rural population (% of total population),SP.RUR.TOTL.ZS,8.739200e+01,1960
419773,Zimbabwe,ZWE,Rural population growth (annual %),SP.RUR.TOTL.ZG,2.959891e+00,1960
419864,Zimbabwe,ZWE,"Survival to age 65, female (% of cohort)",SP.DYN.TO65.FE.ZS,4.947769e+01,1960
419865,Zimbabwe,ZWE,"Survival to age 65, male (% of cohort)",SP.DYN.TO65.MA.ZS,4.335591e+01,1960
419882,Zimbabwe,ZWE,Taxes less subsidies on products (current LCU),NY.TAX.NIND.CN,4.696610e+07,1960
419883,Zimbabwe,ZWE,Taxes less subsidies on products (current US$),NY.TAX.NIND.CD,4.696610e+07,1960
419924,Zimbabwe,ZWE,Total fisheries production (metric tons),ER.FSH.PROD.MT,1.300000e+03,1960
419935,Zimbabwe,ZWE,"Trademark applications, direct nonresident",IP.TMK.NRES,1.438000e+03,1960
419936,Zimbabwe,ZWE,"Trademark applications, direct resident",IP.TMK.RESD,4.960000e+02,1960
419939,Zimbabwe,ZWE,"Trademark applications, total",IP.TMK.TOTL,1.934000e+03,1960
419994,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4.724680e+05,1960
419995,Zimbabwe,ZWE,Urban population (% of total),SP.URB.TOTL.IN.ZS,1.260800e+01,1960
419996,Zimbabwe,ZWE,Urban population growth (annual %),SP.URB.GROW,4.879355e+00,1960

In [140]:
# Changing the header names
names = ['CountryName', 'CountryCode', 'IndicatorName', 'IndicatorCode', 'Value', 'Year']

In [137]:
# Define lists2dict()
def lists2dict(list1, list2):
    """Return a dictionary where list1 provides
    the keys and list2 provides the values."""

    # Zip lists: zipped_lists
    zipped_lists = zip(list1, list2)

    # Create a dictionary: rs_dict
    rs_dict = dict(zipped_lists)

    # Return the dictionary
    return rs_dict

In [139]:
# Import the pandas package
import pandas as pd

# Turn list of lists into list of dicts: list_of_dicts
list_of_dicts = [lists2dict(names, sublist) for sublist in df1.values]

# Turn list of dicts into a dataframe: df2
df2 = pd.DataFrame(list_of_dicts)
print(df2.shape)

# Turn the first 2900 rows into df3
df3 = df2.iloc[0:2900,:] 

# Print df3
df3

(38447, 6)

,CountryCode,CountryName,IndicatorCode,IndicatorName,Value,Year
0,ARB,Arab World,SP.ADO.TFRT,"Adolescent fertility rate (births per 1,000 wo...",1.342236e+02,1960
1,ARB,Arab World,SP.POP.DPND,Age dependency ratio (% of working-age populat...,8.820581e+01,1960
2,ARB,Arab World,SP.POP.DPND.OL,"Age dependency ratio, old (% of working-age po...",6.602746e+00,1960
3,ARB,Arab World,SP.POP.DPND.YG,"Age dependency ratio, young (% of working-age ...",8.146539e+01,1960
4,ARB,Arab World,ER.FSH.AQUA.MT,Aquaculture production (metric tons),4.600000e+03,1960
5,ARB,Arab World,MS.MIL.XPRT.KD,Arms exports (SIPRI trend indicator values),3.000000e+06,1960
6,ARB,Arab World,MS.MIL.MPRT.KD,Arms imports (SIPRI trend indicator values),5.390000e+08,1960
7,ARB,Arab World,SP.DYN.CBRT.IN,"Birth rate, crude (per 1,000 people)",4.768996e+01,1960
8,ARB,Arab World,FM.LBL.BMNY.GD.ZS,Broad money (% of GDP),2.249595e+01,1960
9,ARB,Arab World,ER.FSH.CAPT.MT,Capture fisheries production (metric tons),4.748800e+05,1960
10,ARB,Arab World,FS.AST.CGOV.GD.ZS,"Claims on central government, etc. (% GDP)",4.083131e-01,1960
11,ARB,Arab World,EN.ATM.CO2E.KT,CO2 emissions (kt),5.953540e+04,1960
12,ARB,Arab World,EN.ATM.CO2E.PC,CO2 emissions (metric tons per capita),6.436890e-01,1960
13,ARB,Arab World,EN.ATM.CO2E.GF.ZS,CO2 emissions from gaseous fuel consumption (%...,5.041292e+00,1960
14,ARB,Arab World,EN.ATM.CO2E.LF.ZS,CO2 emissions from liquid fuel consumption (% ...,8.485147e+01,1960
15,ARB,Arab World,EN.ATM.CO2E.LF.KT,CO2 emissions from liquid fuel consumption (kt),5.053980e+04,1960
16,ARB,Arab World,EN.ATM.CO2E.SF.ZS,CO2 emissions from solid fuel consumption (% o...,4.726981e+00,1960
17,ARB,Arab World,SP.DYN.CDRT.IN,"Death rate, crude (per 1,000 people)",1.985420e+01,1960
18,ARB,Arab World,FS.AST.DOMS.GD.ZS,Domestic credit provided by financial sector (...,1.303565e+01,1960
19,ARB,Arab World,FS.AST.PRVT.GD.ZS,Domestic credit to private sector (% of GDP),1.224533e+01,1960
20,ARB,Arab World,FD.AST.PRVT.GD.ZS,Domestic credit to private sector by banks (% ...,1.167700e+01,1960
21,ARB,Arab World,SP.DYN.TFRT.IN,"Fertility rate, total (births per woman)",6.948747e+00,1960
22,ARB,Arab World,SH.MED.BEDS.ZS,"Hospital beds (per 1,000 people)",1.931232e+00,1960
23,ARB,Arab World,SM.POP.TOTL,"International migrant stock, total",3.324685e+06,1960
24,ARB,Arab World,SP.DYN.LE00.FE.IN,"Life expectancy at birth, female (years)",4.790606e+01,1960
25,ARB,Arab World,SP.DYN.LE00.MA.IN,"Life expectancy at birth, male (years)",4.577688e+01,1960
26,ARB,Arab World,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",4.682506e+01,1960
27,ARB,Arab World,TX.VAL.MRCH.CD.WT,Merchandise exports (current US$),4.644054e+09,1960
28,ARB,Arab World,TX.VAL.MRCH.WL.CD,Merchandise exports by the reporting economy (...,2.467200e+09,1960
29,ARB,Arab World,TX.VAL.MRCH.RS.ZS,"Merchandise exports by the reporting economy, ...",1.539397e+01,1960
...,...,...,...,...,...,...
2870,IDB,IDA blend,SP.POP.0014.FE.ZS,"Population ages 0-14, female (% of total)",4.101598e+01,1960
2871,IDB,IDA blend,SP.POP.0014.MA.IN,"Population ages 0-14, male",2.542341e+07,1960
2872,IDB,IDA blend,SP.POP.0014.MA.ZS,"Population ages 0-14, male (% of total)",4.044707e+01,1960
2873,IDB,IDA blend,SP.POP.0014.TO,"Population ages 0-14, total",5.014747e+07,1960
2874,IDB,IDA blend,SP.POP.0004.FE.5Y,"Population ages 0-4, female (% of female popul...",1.687831e+01,1960
2875,IDB,IDA blend,SP.POP.0004.MA.5Y,"Population ages 0-4, male (% of male population)",1.662534e+01,1960
2876,IDB,IDA blend,SP.POP.1014.FE.5Y,"Population ages 10-14, female (% of female pop...",1.103865e+01,1960
2877,IDB,IDA blend,SP.POP.1014.MA.5Y,"Population ages 10-14, male (% of male populat...",1.103531e+01,1960
2878,IDB,IDA blend,SP.POP.1519.FE.5Y,"Population ages 15-19, female (% of female pop...",9.815507e+00,1960
2879,IDB,IDA blend,SP.POP.1519.MA.5Y,"Population ages 15-19, male (% of male populat...",9.938145e+00,1960
2880,IDB,IDA blend,SP.POP.1564.TO.ZS,Population ages 15-64 (% of total),5.548654e+01,1960
2881,IDB,IDA blend,SP.POP.1564.FE.IN,"Population ages 15-64, female",3.312706e+07,1960
2882,IDB,IDA blend,SP.POP.1564.FE.ZS,"Population ages 15-64, female (% of total)",5.495617e+01,1960
2883,IDB,IDA blend,SP.POP.1564.MA.IN,"Population ages 15-64, male",3.519633e+07,1960
2884,IDB,IDA blend,SP.POP.1564.MA.ZS,"Population ages 15-64, male (% of total)",5.599518e+01,1960
2885,IDB,IDA blend,SP.POP.1564.TO,"Population ages 15-64, total",6.832338e+07,1960
2886,IDB,IDA blend,SP.POP.2024.FE.5Y,"Population ages 20-24, female (% of female pop...",8.695021e+00,1960
2887,IDB,IDA blend,SP.POP.2024.MA.5Y,"Population ages 20-24, male (% of male populat...",8.826045e+00,1960
2888,IDB,IDA blend,SP.POP.2529.FE.5Y,"Population ages 25-29, female (% of female pop...",7.527888e+00,1960
2889,IDB,IDA blend,SP.POP.2529.MA.5Y,"Population ages 25-29, male (% of male populat...",7.688492e+00,1960
2890,IDB,IDA blend,SP.POP.3034.FE.5Y,"Population ages 30-34, female (% of female pop...",6.515896e+00,1960
2891,IDB,IDA blend,SP.POP.3034.MA.5Y,"Population ages 30-34, male (% of male populat...",6.777351e+00,1960
2892,IDB,IDA blend,SP.POP.3539.FE.5Y,"Population ages 35-39, female (% of female pop...",5.496385e+00,1960
2893,IDB,IDA blend,SP.POP.3539.MA.5Y,"Population ages 35-39, male (% of male populat...",5.683376e+00,1960
2894,IDB,IDA blend,SP.POP.4044.FE.5Y,"Population ages 40-44, female (% of female pop...",4.565200e+00,1960
2895,IDB,IDA blend,SP.POP.4044.MA.5Y,"Population ages 40-44, male (% of male populat...",4.771916e+00,1960
2896,IDB,IDA blend,SP.POP.4549.FE.5Y,"Population ages 45-49, female (% of female pop...",3.921089e+00,1960
2897,IDB,IDA blend,SP.POP.4549.MA.5Y,"Population ages 45-49, male (% of male populat...",4.058509e+00,1960
2898,IDB,IDA blend,SP.POP.5054.FE.5Y,"Population ages 50-54, female (% of female pop...",3.288414e+00,1960
2899,IDB,IDA blend,SP.POP.5054.MA.5Y,"Population ages 50-54, male (% of male populat...",3.353508e+00,1960

In [131]:
# Rearranging columns by directly specifying the order
df3 = df3[['CountryName', 'CountryCode', 'IndicatorName', 'IndicatorCode', 'Year', 'Value']]

In [132]:
df3

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,1.342236e+02
1,Arab World,ARB,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,8.820581e+01
2,Arab World,ARB,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,6.602746e+00
3,Arab World,ARB,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,8.146539e+01
4,Arab World,ARB,Aquaculture production (metric tons),ER.FSH.AQUA.MT,1960,4.600000e+03
5,Arab World,ARB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,1960,3.000000e+06
6,Arab World,ARB,Arms imports (SIPRI trend indicator values),MS.MIL.MPRT.KD,1960,5.390000e+08
7,Arab World,ARB,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,1960,4.768996e+01
8,Arab World,ARB,Broad money (% of GDP),FM.LBL.BMNY.GD.ZS,1960,2.249595e+01
9,Arab World,ARB,Capture fisheries production (metric tons),ER.FSH.CAPT.MT,1960,4.748800e+05
10,Arab World,ARB,"Claims on central government, etc. (% GDP)",FS.AST.CGOV.GD.ZS,1960,4.083131e-01
11,Arab World,ARB,CO2 emissions (kt),EN.ATM.CO2E.KT,1960,5.953540e+04
12,Arab World,ARB,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1960,6.436890e-01
13,Arab World,ARB,CO2 emissions from gaseous fuel consumption (%...,EN.ATM.CO2E.GF.ZS,1960,5.041292e+00
14,Arab World,ARB,CO2 emissions from liquid fuel consumption (% ...,EN.ATM.CO2E.LF.ZS,1960,8.485147e+01
15,Arab World,ARB,CO2 emissions from liquid fuel consumption (kt),EN.ATM.CO2E.LF.KT,1960,5.053980e+04
16,Arab World,ARB,CO2 emissions from solid fuel consumption (% o...,EN.ATM.CO2E.SF.ZS,1960,4.726981e+00
17,Arab World,ARB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,1960,1.985420e+01
18,Arab World,ARB,Domestic credit provided by financial sector (...,FS.AST.DOMS.GD.ZS,1960,1.303565e+01
19,Arab World,ARB,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1960,1.224533e+01
20,Arab World,ARB,Domestic credit to private sector by banks (% ...,FD.AST.PRVT.GD.ZS,1960,1.167700e+01
21,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,1960,6.948747e+00
22,Arab World,ARB,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,1960,1.931232e+00
23,Arab World,ARB,"International migrant stock, total",SM.POP.TOTL,1960,3.324685e+06
24,Arab World,ARB,"Life expectancy at birth, female (years)",SP.DYN.LE00.FE.IN,1960,4.790606e+01
25,Arab World,ARB,"Life expectancy at birth, male (years)",SP.DYN.LE00.MA.IN,1960,4.577688e+01
26,Arab World,ARB,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,1960,4.682506e+01
27,Arab World,ARB,Merchandise exports (current US$),TX.VAL.MRCH.CD.WT,1960,4.644054e+09
28,Arab World,ARB,Merchandise exports by the reporting economy (...,TX.VAL.MRCH.WL.CD,1960,2.467200e+09
29,Arab World,ARB,"Merchandise exports by the reporting economy, ...",TX.VAL.MRCH.RS.ZS,1960,1.539397e+01
...,...,...,...,...,...,...
2870,IDA blend,IDB,"Population ages 0-14, female (% of total)",SP.POP.0014.FE.ZS,1960,4.101598e+01
2871,IDA blend,IDB,"Population ages 0-14, male",SP.POP.0014.MA.IN,1960,2.542341e+07
2872,IDA blend,IDB,"Population ages 0-14, male (% of total)",SP.POP.0014.MA.ZS,1960,4.044707e+01
2873,IDA blend,IDB,"Population ages 0-14, total",SP.POP.0014.TO,1960,5.014747e+07
2874,IDA blend,IDB,"Population ages 0-4, female (% of female popul...",SP.POP.0004.FE.5Y,1960,1.687831e+01
2875,IDA blend,IDB,"Population ages 0-4, male (% of male population)",SP.POP.0004.MA.5Y,1960,1.662534e+01
2876,IDA blend,IDB,"Population ages 10-14, female (% of female pop...",SP.POP.1014.FE.5Y,1960,1.103865e+01
2877,IDA blend,IDB,"Population ages 10-14, male (% of male populat...",SP.POP.1014.MA.5Y,1960,1.103531e+01
2878,IDA blend,IDB,"Population ages 15-19, female (% of female pop...",SP.POP.1519.FE.5Y,1960,9.815507e+00
2879,IDA blend,IDB,"Population ages 15-19, male (% of male populat...",SP.POP.1519.MA.5Y,1960,9.938145e+00
2880,IDA blend,IDB,Population ages 15-64 (% of total),SP.POP.1564.TO.ZS,1960,5.548654e+01
2881,IDA blend,IDB,"Population ages 15-64, female",SP.POP.1564.FE.IN,1960,3.312706e+07
2882,IDA blend,IDB,"Population ages 15-64, female (% of total)",SP.POP.1564.FE.ZS,1960,5.495617e+01
2883,IDA blend,IDB,"Population ages 15-64, male",SP.POP.1564.MA.IN,1960,3.519633e+07
2884,IDA blend,IDB,"Population ages 15-64, male (% of total)",SP.POP.1564.MA.ZS,1960,5.599518e+01
2885,IDA blend,IDB,"Population ages 15-64, total",SP.POP.1564.TO,1960,6.832338e+07
2886,IDA blend,IDB,"Population ages 20-24, female (% of female pop...",SP.POP.2024.FE.5Y,1960,8.695021e+00
2887,IDA blend,IDB,"Population ages 20-24, male (% of male populat...",SP.POP.2024.MA.5Y,1960,8.826045e+00
2888,IDA blend,IDB,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,1960,7.527888e+00
2889,IDA blend,IDB,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,1960,7.688492e+00
2890,IDA blend,IDB,"Population ages 30-34, female (% of female pop...",SP.POP.3034.FE.5Y,1960,6.515896e+00
2891,IDA blend,IDB,"Population ages 30-34, male (% of male populat...",SP.POP.3034.MA.5Y,1960,6.777351e+00
2892,IDA blend,IDB,"Population ages 35-39, female (% of female pop...",SP.POP.3539.FE.5Y,1960,5.496385e+00
2893,IDA blend,IDB,"Population ages 35-39, male (% of male populat...",SP.POP.3539.MA.5Y,1960,5.683376e+00
2894,IDA blend,IDB,"Population ages 40-44, female (% of female pop...",SP.POP.4044.FE.5Y,1960,4.565200e+00
2895,IDA blend,IDB,"Population ages 40-44, male (% of male populat...",SP.POP.4044.MA.5Y,1960,4.771916e+00
2896,IDA blend,IDB,"Population ages 45-49, female (% of female pop...",SP.POP.4549.FE.5Y,1960,3.921089e+00
2897,IDA blend,IDB,"Population ages 45-49, male (% of male populat...",SP.POP.4549.MA.5Y,1960,4.058509e+00
2898,IDA blend,IDB,"Population ages 50-54, female (% of female pop...",SP.POP.5054.FE.5Y,1960,3.288414e+00
2899,IDA blend,IDB,"Population ages 50-54, male (% of male populat...",SP.POP.5054.MA.5Y,1960,3.353508e+00

In [136]:
# Writing DataFrame to CSV file without index
df3.to_csv('world_dev_ind.csv', index=False)

## 4) Processing data in chunks

* Processing a file line by line for a given number of lines (1000)
* Counting the number of ocurrences of the first column value

In [146]:
# Open connection to file 'world_dev_ind.csv'
with open('world_dev_ind.csv') as file:
    
    # Skipe the column names
    file.readline()
    
    # Initialize an empty dictionary
    counts_dict = {}
    
    # Process only the first 1000 rows
    for i in range(0,1000):
        
        # Split the current line into a list
        line = file.readline().split(',')
        
        # Get the value for the first column
        first_col = line[0]
        
        # If the column value is in the dict, increment its value
        if first_col in counts_dict.keys():
            counts_dict[first_col] += 1
        else:
            counts_dict[first_col] = 1
            
for key, value in counts_dict.items():
    print("{} : {} times".format(key,value))

Arab World : 139 times
Caribbean small states : 135 times
Central Europe and the Baltics : 132 times
Early-demographic dividend : 200 times
East Asia & Pacific : 178 times
East Asia & Pacific (excluding high income) : 175 times
East Asia & Pacific (IDA & IBRD countries) : 41 times

### * Writing a generator to load data in chunks

* We will write a `Generator` function to process the entire file this time
* `'Lazy Evaluation'` is useful when dealing with `very large datasets`
* It lets you generate values in an efficient manner by `yielding` only `chunks` of data at a time

In [151]:
def read_large_file(file_object):
    """ 
    A generator function to read a
    large file lazily 
    """
    
    # Loop indefinitely until the end of the file
    while True:
        
        # Read a line from the file
        data = file_object.readline()
        
        # Break if this is the end of the file
        if not data:
            break
            
        # Yield the line of data
        yield data

In [152]:
with open('world_dev_ind.csv') as file:
    
    # Create a generator object for the file
    gen_file = read_large_file(file)
    
    # Print generator object
    print(gen_file)
    
    # Print the first three lines if the file
    print(next(gen_file))
    print(next(gen_file))
    print(next(gen_file))

<generator object read_large_file at 0x0000019604D26DE0>
CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value

Arab World,ARB,"Adolescent fertility rate (births per 1,000 women ages 15-19)",SP.ADO.TFRT,1960,134.223612133481

Arab World,ARB,Age dependency ratio (% of working-age population),SP.POP.DPND,1960,88.2058102041107